version: "3.7"
services:
  sequelize-mariadb:
    image: mariadb:10.8.3
    init: true
    container_name: sequelize-mariadb
    ports:
      - "3306:3306"
    env_file:
      - mariadb_env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d